rest_calls:
  - path: /api/v1/applications
    method: POST
    headers:
      Content-type: application/json
      Authorization: "Bearer {{ TOKEN }}"
    payload:
      metadata:
        name: "{{ NAME }}"
      spec:
        destination:
          name: ''
          namespace: default
          server: 'https://kubernetes.default.svc'
        source:
          path: manifests
          repoURL: "{{ REPO }}"
          targetRevision: HEAD
        project: default
      name: ''
      namespace: default
      server: 'https://kubernetes.default.svc'
    response_format: json
    recoverable_codes: [400]
    retry_on_connection_error: true
    response_translation:
        metadata: [metadata]
