rest_calls:
  - path: /api/v1/applications/{{ NAME }}
    method: DELETE
    headers:
      Authorization: "Bearer {{ TOKEN }}"
    payload:
    response_format: json
    recoverable_codes: [400]
    retry_on_connection_error: true
    response_translation:
