rest_calls:
  - path: /api/v1/applications/{{ NAME }}/sync
    method: POST
    headers:
      Content-type: application/json
      Authorization: "Bearer {{ TOKEN }}"
    payload:
      name: "{{ NAME }}"
    response_format: json
    recoverable_codes: [400]
    retry_on_connection_error: true
    response_translation:
        metadata: [metadata]
